// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy7X0oIc7WDrasZCqSkTGoW9l5qSk0svg',
    appId: '1:338318260423:web:d4a3dc221d0ea10d9d66e2',
    messagingSenderId: '338318260423',
    projectId: 'edunity-1',
    authDomain: 'edunity-1.firebaseapp.com',
    storageBucket: 'edunity-1.firebasestorage.app',
    measurementId: 'G-Z30H88B07Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW21MRBnaR8GoHzzuj1669kT0bIVpLEQ0',
    appId: '1:338318260423:android:c48f4bd13c66ca519d66e2',
    messagingSenderId: '338318260423',
    projectId: 'edunity-1',
    storageBucket: 'edunity-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzj9U3jRS-akSWuI0lo30GmKVRuXITUyE',
    appId: '1:338318260423:ios:aa15d1e407055b2e9d66e2',
    messagingSenderId: '338318260423',
    projectId: 'edunity-1',
    storageBucket: 'edunity-1.firebasestorage.app',
    iosBundleId: 'com.depi.edunity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzj9U3jRS-akSWuI0lo30GmKVRuXITUyE',
    appId: '1:338318260423:ios:aa15d1e407055b2e9d66e2',
    messagingSenderId: '338318260423',
    projectId: 'edunity-1',
    storageBucket: 'edunity-1.firebasestorage.app',
    iosBundleId: 'com.depi.edunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy7X0oIc7WDrasZCqSkTGoW9l5qSk0svg',
    appId: '1:338318260423:web:627a3b87041ed0779d66e2',
    messagingSenderId: '338318260423',
    projectId: 'edunity-1',
    authDomain: 'edunity-1.firebaseapp.com',
    storageBucket: 'edunity-1.firebasestorage.app',
    measurementId: 'G-KXL6JWPBD3',
  );
}
